const deps = {
  api: {
    dependencies: [
      "compression",
      "cors",
      "dotenv",
      "envalid",
      "express",
      "helmet",
      "joi",
      "mongodb",
      "mongoose",
      "morgan",
    ],
    devDependencies: [
      "@types/chai",
      "@types/compression",
      "@types/cors",
      "@types/express",
      "@types/mocha",
      "@types/mongodb",
      "@types/mongoose",
      "@types/morgan",
      "@types/node",
      "@types/supertest",
      "@typescript-eslint/eslint-plugin",
      "@typescript-eslint/parser",
      "jest",
      "mocha",
      "nodemon",
      "prettier",
      "supertest",
      "ts-node",
      "tsconfig-paths",
      "typescript",
      "eslint-config-standard",
      "eslint-plugin-import",
      "eslint-plugin-node",
      "eslint-plugin-promise",
      "chai",
      "eslint",
    ],
  },
  webApp: {
    dependencies: [
      "compression",
      "cors",
      "dotenv",
      "envalid",
      "express",
      "helmet",
      "joi",
      "mongodb",
      "mongoose",
      "morgan",
      "ejs",
    ],
    devDependencies: [
      "@types/chai",
      "@types/compression",
      "@types/cors",
      "@types/express",
      "@types/mocha",
      "@types/mongodb",
      "@types/mongoose",
      "@types/morgan",
      "@types/node",
      "@types/supertest",
      "@typescript-eslint/eslint-plugin",
      "@typescript-eslint/parser",
      "jest",
      "mocha",
      "nodemon",
      "prettier",
      "supertest",
      "ts-node",
      "tsconfig-paths",
      "typescript",
      "eslint-config-standard",
      "eslint-plugin-import",
      "eslint-plugin-node",
      "eslint-plugin-promise",
      "chai",
      "eslint",
    ],
  },
};
export default deps;
